---
- name: Install git
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - git
  when: mode == 'dev'

- name: Install mysql client tools
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - mysql-client
  when: mode == 'stage'

- name: Add system group
  group: name="{{ system_group }}"

- name: Add system user
  user: name="{{ system_user }}" group="{{ system_group }}" home="/home/{{ system_user }}"

- name: Configure ~/.my.cnf
  template: src=my.cnf.j2 dest="/home/{{ system_user }}/.my.cnf" owner="{{ system_user }}" group="{{ system_group }}"

- name: Ensure .ssh directory exists
  file: path="/home/{{ system_user }}/.ssh" state=directory mode=0700 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Ensure ~/wpconfigs directory exists
  file: path="/home/{{ system_user }}/wpconfigs" state=directory mode=0700 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'stage'

# wp-cli is used for automating wp admin tasks
- name: Copy wp-cli.phar to system_user home
  copy:
    src: wp-cli.phar
    dest: "/home/{{ system_user }}/wp"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0775

- name: Copy aws deploy key
  template: 
    src: wordpress_deploy_key.j2
    dest: "/home/{{ system_user }}/.ssh/id_rsa"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0600
  when: mode == 'dev'

- name: gitconfig template
  template: src=gitconfig.j2 dest="/home/{{ system_user }}/.gitconfig" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Create installation folder (web_root)
  file: path="{{ web_root }}" owner="{{ system_user }}" group="{{ system_group }}" state=directory mode='u=rwX,g=rwX,o=r'

- name: git checkout repository for site
  git: repo="{{ gitrepo }}"
       version="{{ git_branch }}"
       dest="{{ web_root }}"
       ssh_opts="-o StrictHostKeyChecking=no -vvvv"
       accept_hostkey=True
       force=true
       key_file="/home/{{ system_user }}/.ssh/id_rsa"
  when: mode == 'dev'


- name: chown web files to system user and set permissions
  file:
    path: "{{ web_root }}"
    recurse: yes
    mode: u=rwX,g=rX,o=rX
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
  when: mode == 'dev'

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: Create app config file (stage / prod)
  template:
    src: wp-config.php.j2
    dest: "/home/{{ system_user }}/wpconfigs/wp-config-{{ item.key }}.php"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
  with_dict: "{{ db_hosts }}"
  when: mode == "stage" and db_hosts is defined

- name: Create app config file (dev)
  template: src=wp-config.php.j2 dest="{{ web_root }}/wp-config.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Ensure wp-content/w3tc-config directory exists
  file: path="{{ web_root }}/wp-content/w3tc-config" state=directory mode=0755 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Create w3tc config file (stage / prod)
  template:
    src: master.php.j2 
    dest: "/home/{{ system_user }}/wpconfigs/master-{{ item.key }}.php"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
  with_dict: "{{ cdn_options }}"
  when: mode == "stage" and cdn_options is defined

- name: Create w3 Total Cache master config file
  template: src=master.php.j2 dest="{{ web_root }}/wp-content/w3tc-config/master.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: aws_s3_access_key is defined and mode == 'dev'

- name: Create w3 Total Cache master-admin config file
  template: src=master.php.j2 dest="{{ web_root }}/wp-content/w3tc-config/master-admin.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: aws_s3_access_key is defined and mode == 'dev'

- name: Create dev-refresh shell script
  template:
    src: refresh-dev.sh.j2
    dest: "/home/{{ system_user }}/refresh-dev.sh"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0775
  when: mode == "dev"
  tags: devrefreshscripts

- name: Create dev-refresh php script
  template:
    src: refresh_dev.php.j2
    dest: "{{ web_root }}/refresh_dev.php"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0775
  when: mode == "dev"
  tags: devrefreshscripts

- name: Copy post-receive.php as github post receive webhook
  template: src=post-receive.php.j2 dest="{{ web_root }}/post-receive.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Ensure uploads directory exists
  file: path="{{ web_root }}/wp-content/uploads" state=directory mode=0775 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Ensure writable directories
  file: dest="{{ item }}" state=directory mode=0775 recurse=yes owner="{{ system_user }}" group="{{ system_group }}"
  with_items:
    - "{{ web_root }}/wp-content"
  when: mode == 'dev'
    
- name: Copy Git.php script. Required for git-status.php and git-commit.php
  copy: src="Git.php" dest="{{ web_root }}/Git.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"
  tags: "gitscripts"

- name: Generate git-status.php for server-side git status check
  template: src=git-status.php.j2 dest="{{ web_root }}/git_status.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"
  tags: "gitscripts"

- name: Generate git-commit.php for server-side git commit of modified files
  template: src=git-commit.php.j2 dest="{{ web_root }}/git_commit.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"
  tags: "gitscripts"

- name: Copy site robots.txt (stage)
  copy:
    src: robots.txt
    dest: "/home/{{ system_user }}/wpconfigs/robots.txt"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
  when: mode == "stage"
  tags:
    - robotstxt

- name: Copy site robots.txt (dev)
  copy:
    src: robots.txt
    dest: "{{ web_root }}/robots.txt"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
  when: mode == "dev"
  tags:
    - robotstxt

- name: Add Disallow / for dev sites
  lineinfile: "dest={{ web_root }}/robots.txt regexp='^Disallow: /$' line='Disallow: /' insertafter='^User-agent'"
  when: mode == "dev"
  tags:
    - robotstxt

